### PR TITLE
Use KVariable in weight mappings

### LINKED ISSUE #4: The initializer name schema is violated by Zero and Ones ops
If you will load a graph from Keras in hdf5 format it could keep Zeros or Ones as a default initializer for biases.
But the standard schema of loading weights via initializers names doesn't work well in this way. Should be used another initializer (maybe special) for handling this issue.

Name: Init_conv2d_25_conv2d_bias/Zero; Type: Const; Out #tensors:  1
Name: Init_conv2d_25_conv2d_bias/Fill; Type: Fill; Out #tensors:  1

### PR DESCRIPTION
**Pull request by juliabeliaeva**
This PR refactors loading model weight, to use `KVariable` in the code. This will allow later to deal with #4 by taking the initialiser from the `KVariable` instance instead of trying to find it by name.

### CODE REVIEW

File: api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt [hunk 1]
```diff
@@ -55,154 +55,102 @@ internal object WeightMappings {
...
 
-    private fun getConv2DVariablePathTemplates(layer: Conv2D, layerPaths: LayerPaths?): Map<String, String> {
+    private fun getConv2DVariablePathTemplates(layer: Conv2D, layerPaths: LayerPaths?): Map<KVariable, String> {
         val layerConvOrDensePaths = layerPaths as? LayerConvOrDensePaths
             ?: LayerConvOrDensePaths(layer.name, KERNEL_DATA_PATH_TEMPLATE, BIAS_DATA_PATH_TEMPLATE)
-        val variables = mutableMapOf(
-            Pair(convKernelVarName(layer.name, dim = 2), layerConvOrDensePaths.kernelPath)
+        return mapOfNotNull(
+            layer.kernel to layerConvOrDensePaths.kernelPath,
+            layer.bias to layerConvOrDensePaths.biasPath
```
Comment (zaleslaw) [inline api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt:67]: does it correctly handle the situation when the layer.useBias = false?

File: api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt [hunk 2]
```diff
@@ -55,154 +55,102 @@ internal object WeightMappings {
...
-    private fun getConv2DVariables(layer: Conv2D): Map<String, Pair<String, LongArray>> {
-        val variables = mutableMapOf(
-            Pair("kernel:0", Pair(convKernelVarName(layer.name, dim = 2), layer.kernelShapeArray!!))
-        )
-        if (layer.useBias) {
-            variables["bias:0"] = Pair(convBiasVarName(layer.name, dim = 2), layer.biasShapeArray!!)
-        }
-        return variables
+    private fun getConv2DVariables(layer: Conv2D): Map<String, KVariable> {
+        return mapOfNotNull("kernel:0" to layer.kernel, "bias:0" to layer.bias)
```
Comment (zaleslaw) [inline api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt:59]: does it correctly handle the situation when the layer.useBias = false?

File: api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt [hunk 3]
```diff
@@ -55,154 +55,102 @@ internal object WeightMappings {
...
+    private fun getConvTransposeVariablePathTemplates(layer: ConvTranspose,
+                                                      layerPaths: LayerPaths?
+    ): Map<KVariable, String> {
         val layerConvOrDensePaths = layerPaths as? LayerConvOrDensePaths
             ?: LayerConvOrDensePaths(layer.name, KERNEL_DATA_PATH_TEMPLATE, BIAS_DATA_PATH_TEMPLATE)
-        val variables = mutableMapOf(
-            Pair(convTransposeKernelVarName(layer.name, layer.dimensions), layerConvOrDensePaths.kernelPath)
+        return mapOfNotNull(
+            layer.kernel to layerConvOrDensePaths.kernelPath,
+            layer.bias to layerConvOrDensePaths.biasPath
```
Comment (zaleslaw) [inline api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt:82]: does it correctly handle the situation when the layer.useBias = false?

File: api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt [hunk 4]
```diff
@@ -55,154 +55,102 @@ internal object WeightMappings {
...
-            ),
-            Pair(
-                "pointwise_kernel:0",
-                Pair(separableConv2dPointwiseKernelVarName(layer.name), layer.pointwiseShapeArray!!)
-            )
+    private fun getSeparableConv2DVariables(layer: SeparableConv2D): Map<String, KVariable> {
+        return mapOfNotNull(
+            "depthwise_kernel:0" to layer.depthwiseKernel,
+            "pointwise_kernel:0" to layer.pointwiseKernel,
+            "bias:0" to layer.bias
```
Comment (zaleslaw) [inline api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt:109]: does it correctly handle the situation when the layer.useBias = false?

File: api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt [hunk 5]
```diff
@@ -55,154 +55,102 @@ internal object WeightMappings {
...
-    private fun getDenseVariables(layer: Dense): Map<String, Pair<String, LongArray>> {
-        val variables = mutableMapOf(
-            Pair("kernel:0", Pair(denseKernelVarName(layer.name), layer.kernelShapeArray!!))
-        )
-        if (layer.useBias) {
-            variables["bias:0"] = Pair(denseBiasVarName(layer.name), layer.biasShapeArray!!)
-        }
-        return variables
+    private fun getDenseVariables(layer: Dense): Map<String, KVariable> {
+        return mapOfNotNull("kernel:0" to layer.kernel, "bias:0" to layer.bias)
```
Comment (zaleslaw) [inline api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt:131]: does it correctly handle the situation when the layer.useBias = false?

File: api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt [hunk 6]
```diff
@@ -55,154 +55,102 @@ internal object WeightMappings {
...
 
-    private fun getDenseVariablesPathTemplates(layer: Dense, layerPaths: LayerPaths?): Map<String, String> {
+    private fun getDenseVariablesPathTemplates(layer: Dense, layerPaths: LayerPaths?): Map<KVariable, String> {
         val layerConvOrDensePaths = layerPaths as? LayerConvOrDensePaths
             ?: LayerConvOrDensePaths(layer.name, KERNEL_DATA_PATH_TEMPLATE, BIAS_DATA_PATH_TEMPLATE)
-        val variables = mutableMapOf(
-            Pair(denseKernelVarName(layer.name), layerConvOrDensePaths.kernelPath)
+        return mapOfNotNull(
+            layer.kernel to layerConvOrDensePaths.kernelPath,
+            layer.bias to layerConvOrDensePaths.biasPath
```
Comment (zaleslaw) [inline api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt:139]: does it correctly handle the situation when the layer.useBias = false?

File: api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt [hunk 7]
```diff
@@ -211,17 +159,22 @@ internal object WeightMappings {
                 MOVING_MEAN_DATA_PATH_TEMPLATE,
                 MOVING_VARIANCE_DATA_PATH_TEMPLATE
             )
-        val variables = mutableMapOf(
-            Pair(batchNormMovingMeanVarName(layer.name), layerBatchNormPaths.movingMeanPath),
-            Pair(batchNormMovingVarianceVarName(layer.name), layerBatchNormPaths.movingVariancePath)
+        return mapOfNotNull(
+            layer.movingMean to layerBatchNormPaths.movingMeanPath,
+            layer.movingVariance to layerBatchNormPaths.movingVariancePath,
+            layer.gamma to layerBatchNormPaths.gammaPath,
```
Comment (zaleslaw) [inline api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt:165]: does it correctly handle the situation when the layer.scale= false or layer.center = false?

File: api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt [hunk 8]
```diff
@@ -211,17 +159,22 @@ internal object WeightMappings {
...
+            layer.beta to layerBatchNormPaths.betaPath
         )
-        if (layer.scale) {
-            variables[batchNormGammaVarName(layer.name)] = layerBatchNormPaths.gammaPath
-        }
-        if (layer.center) {
-            variables[batchNormBetaVarName(layer.name)] = layerBatchNormPaths.betaPath
+    }
+
+    private fun <K, V> mapOfNotNull(vararg mapping: Pair<K?, V?>): Map<K, V> {
```
Comment (zaleslaw) [inline api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt:170]: Looks like we need to extend the standard library here!
Probably better to move such common things to the high-level util class at the level of project (if something common will be useful again)

**Review by zaleslaw — CHANGES_REQUESTED** [review]
@juliabeliaeva please answer some questions about bias and refactoring

File: api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt (hunk 2 above)
Comment (juliabeliaeva) [reply api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt:59]: Yes. If `layer.useBias` is `false`, then `layer.bias` is `null`, which gets filtered out by `mapOfNotNull`.

File: api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt (hunk 8 above)
Comment (juliabeliaeva) [reply api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt]: Moved the function to a utility file.

File: api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt (hunk 2 above)
Comment (zaleslaw) [reply api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/WeightMappings.kt:60]: Yes, no I see, it's hidden in this procedure

**Comment by zaleslaw** [comment]
@juliabeliaeva LGTM for me, you could merge it by yourself, please use Squash and merge option
